kokonaisluku1 = int(input("Anna ensimmäinen luku:"))
kokonaisluku2 = int(input("Anna toinen luku:"))
kokonaisluku3 = int(input("Anna kolmas luku:"))
print("summa")
print(kokonaisluku1 + kokonaisluku2 + kokonaisluku3)
print("tulo")
print(kokonaisluku1 * kokonaisluku2 * kokonaisluku3)
print("keskiarvo")
print(kokonaisluku1 + kokonaisluku2 + kokonaisluku3 /3)